version: "3.7"
services:
    client:
        build:
           context: ./client
           args:
               - npm_config_registry=$npm_config_registry
        ports:
            - "3000:3000"
        networks:
            - frontend
        volumes:
            - type: volume
              source: node_mods
              target: '/app/node_modules'
            - type: bind
              source: ./client
              target: '/app'
    server:
        build:
            context: ./server
        depends_on:
            - db
        environment:
            - MONGO_HOST
            - MONGO_USER
            - MONGO_PASSWORD
            - MONGO_DATABASE
        ports:
            - "8080:8080"
        networks:
            - backend
            - frontend
    db:
        image: mongo:latest
        ports:
            - "27017"
              #- "27018:27018"
              #- "27019:27019"
        networks:
            - backend
        volumes:
            - type: volume
              source: dbdata
              target: /data/db
            - type: bind
              source: ./build/mongo/docker-entrypoint-initdb.d
              target: /docker-entrypoint-initdb.d
volumes:
    dbdata:
    node_mods:
networks:
    frontend:
    backend:
