version: "3.7"
services:
    #    front:
    #    build:
    #        context:
    server:
        build:
            context: ./server
        depends_on:
            - db
        env_file: ./server/.env.local
        environment:
            - MONGO_HOST=db
        ports:
            - "8080:8080"

        links:
            - db
        networks:
            - default
    db:
        image: mongo:latest
        ports:
            - "27017:27017"
              #- "27018:27018"
              #- "27019:27019"
        volumes:
            - type: volume
              source: dbdata
              target: /data/db
volumes:
    dbdata:
